import { useId, useState } from 'react'
import './App.css'

const projects = [
  { title: 'Attendance Monitoring System', category: 'FULL-STACK WEB / HARDWARE INTEGRATION', description: 'A browser-ready demonstration of the contracted attendance platform, showing the employee timeclock and administrative dashboard workflows connected to RFID, facial recognition, fingerprint integration, attendance reporting, geofenced validation, and offline synchronization.', tags: ['Laravel & PHP', 'Vue & Inertia.js', 'Filament', 'RFID'], type: 'rfid', url: './attendance-monitoring-demo.html', linkLabel: 'Open browser demo' },
  { title: 'Mobile Attendance Prototype', category: 'REACT / LOCATION-BASED ATTENDANCE', description: 'A separate React prototype for field attendance, with an interactive Leaflet map, configurable itinerary locations, and distance-based geofence checks. Developed as a browser-based exploration of mobile attendance workflows.', tags: ['React', 'Leaflet', 'Geolocation'], type: 'rfid', url: './mobile-attendance-demo.html', demoUrl: 'https://yukie1212.github.io/PORTFOLIO/mobile-attendance-demo.html', linkLabel: 'Open mobile demo' },
  { title: 'Attendance Kiosk Integration', category: 'WINDOWS / HARDWARE INTEGRATION', description: 'The hardware integration layer of the attendance platform: a local ZKTeco fingerprint agent, doorway sensing tools, and a kiosk installer. Connects on-site attendance devices with the central Laravel application.', tags: ['Windows agents', 'ZKTeco', 'Kiosk deployment'], type: 'enclosure', url: 'mailto:angelomiguelr.cua@gmail.com?subject=Attendance%20Kiosk%20Integration', linkLabel: 'Discuss the integration' },
  { title: 'ICT & Security Systems — Client Engagements', category: 'NETWORKING / CCTV / SECURITY INSTALLATION', description: 'Layout and installation of ICT and security systems for McAsia Food Trade Corporation, Luxe Prime Realty, Medical Gallery Corporation, and Camfin Lending Inc. Includes network and CCTV installation, Windows Server and Active Directory configuration, firewall setup, NAS and Plex server deployment, and general hardware support.', tags: ['Windows Server', 'Active Directory', 'CCTV', 'Firewall', 'NAS'], type: 'enclosure', url: 'mailto:angelomiguelr.cua@gmail.com?subject=ICT%20and%20Security%20Systems%20Client%20Engagements', linkLabel: 'Discuss client systems' },
  { title: 'McAsia Food Trade Corporation — Power BI Dashboard', category: 'DATA ANALYSIS / BUSINESS INTELLIGENCE', description: 'A reporting and dashboard system designed to turn operational data into clear, executive-ready insights for decision-making. The dashboards consolidate key business metrics, support KPI monitoring, and help visualize trends related to sales, performance, and operational activity across the organization.', tags: ['Power BI', 'KPI Reporting', 'Data Analysis', 'Dashboard Design'], type: 'enclosure', url: '/March%20sales%20report.pbix', linkLabel: 'Open Power BI file' },
  { title: 'Timelight', category: 'EMBEDDED SYSTEMS / PROTOTYPING', description: 'A speech-timing device built with an Arduino Nano, buzzer, and LED lights. Audible and visual cues help speakers keep track of their time.', tags: ['Arduino Nano', 'Embedded systems', 'Prototyping'], type: 'enclosure', url: 'https://badjau.github.io/timelight/', linkLabel: 'Explore Timelight' },
  { title: 'ShopEase: BLE-Enabled Product Locator System with Real-Time Pricing and Dynamic Aisle Mapping for Supermarkets', category: 'BLE / RETAIL TECHNOLOGY / SMART CART SYSTEM', description: 'A supermarket product locator that uses Bluetooth Low Energy to guide shoppers through dynamically mapped aisles, surface real-time pricing, and keep product discovery and basket decisions in one connected experience. A Raspberry Pi 5, IPS DSI display, ESP32 positioning anchor, barcode scanner, and 5V Li-ion UPS support the smart cart interface.', tags: ['BLE positioning', 'Dynamic aisle mapping', 'Real-time pricing', 'Raspberry Pi 5', 'ESP32'], type: 'enclosure', url: 'https://cad.onshape.com/documents/aecccfbb5e0d449d2db2d221/w/9b3be6ea39467a66d63fc874/e/acf9ac63a97a4a71faaf4574', linkLabel: 'Open interactive CAD model' },
  { title: 'RFID Gym Access System', category: 'RESEARCH / WEB + ACCESS CONTROL', description: 'A smart gym access system that verifies registered members through RFID authentication and controls door access with real-time feedback. The setup uses an ESP32 Vroom32, RFID scanner, magnetic lock, 24V buzzer, and red/green indicator LEDs to signal successful or denied access attempts.', tags: ['ESP32 Vroom32', 'RFID', 'Magnetic lock', 'Gym access'], type: 'rfid', url: 'https://cad.onshape.com/documents/a18f28a1a9cb6931ccf0aee3/w/2ab899e5d080cd54efd4ab7b/e/b31c332504ffcc849bf053c9', linkLabel: 'View project details' },
]
const capabilities = [
  ['01', 'Data analysis & reporting', 'Power BI dashboard development, business reporting, KPI tracking, Excel analysis, and data-driven decision support.'],
  ['02', 'IT support & infrastructure', 'Network deployment, structured cabling, hardware diagnostics, CCTV installation, workstation support, and systems maintenance.'],
  ['03', 'Embedded systems & software', 'Python automation, C/C++, PHP, Arduino, ESP32, Raspberry Pi, sensors, IoT integration, and practical hardware solutions.'],
]


function TechnicalArt({ type = 'enclosure' }) {
  const artId = useId()
  return <svg className="technical-art" viewBox="0 0 600 440" fill="none" aria-hidden="true">
    <defs><pattern id={`grid-${artId}`} width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" stroke="currentColor" opacity=".1" /></pattern><linearGradient id={`face-${artId}`} x2="1" y2="1"><stop stopColor="currentColor" stopOpacity=".28"/><stop offset="1" stopColor="currentColor" stopOpacity=".03"/></linearGradient></defs>
    <rect width="600" height="440" fill={`url(#grid-${artId})`}/>
    <g stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round">
    {type === 'enclosure' ? <><path d="M145 236 302 145 462 236 305 330Z" fill={`url(#face-${artId})`}/><path d="M145 236v45l160 93 157-92v-46M305 330v44"/><path d="M145 157 302 66 462 157 305 250Z" fill={`url(#face-${artId})`}/><path d="M145 157v26l160 93 157-92v-27M305 250v26"/><path d="m187 157 115-66 119 66-116 67Z"/><path d="m229 155 73-42 77 44-74 42Z"/><path d="M160 195v30m286-30v30M305 288v31" strokeDasharray="4 5"/><path d="m177 272 58 34m-58-26 58 34m-58-26 58 34"/><circle cx="412" cy="288" r="4"/></> : <><path d="m145 237 157-91 158 91-157 91Z" fill={`url(#face-${artId})`}/><path d="M145 237v20l158 92 157-92v-20M303 328v21"/><path d="m251 235 51-30 54 30-53 31Z"/><path d="m221 235 81-47 84 47-83 49Z"/><path d="m192 235 110-64 113 64-112 66Z"/><path d="M302 203v-64" strokeDasharray="5 6"/><ellipse cx="302" cy="127" rx="39" ry="22"/><ellipse cx="302" cy="103" rx="69" ry="38" opacity=".65"/><ellipse cx="302" cy="79" rx="99" ry="55" opacity=".35"/><path d="m174 250 49 28m159-28 49-28"/></>}
    <path d="M100 315v55m0-12 92 53M90 352l20 12M182 399l20 12M488 168v133m-7-131h14m-14 129h14" opacity=".45"/>
    </g><g fill="currentColor" fontFamily="monospace" fontSize="11" opacity=".65"><text x="35" y="35">{type === 'enclosure' ? 'FIG. 01 / EXPLODED FORM' : 'FIG. 02 / CONNECTED SYSTEM'}</text><text x="35" y="413">CONCEPT DIAGRAM · NOT TO SCALE</text><text x="510" y="413">AMC</text></g>
  </svg>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)

  const scrollToSection = (event, targetId) => {
    const target = document.getElementById(targetId)

    if (event) {
      event.preventDefault()
    }

    if (target) {
      target.scrollIntoView({ behavior: 'smooth', block: 'start' })
      return
    }

    window.location.hash = targetId
  }

  return <div className="page-shell">
    <a className="skip-link" href="#main" onClick={(event) => scrollToSection(event, 'main')}>Skip to content</a>
    <header className="topbar"><a className="brand" href="#home" onClick={(event) => scrollToSection(event, 'home')} aria-label="Angelo Miguel R. Cua, home">amc<span>✳</span></a><span className="header-note">DATA / SOFTWARE / HARDWARE / INFRASTRUCTURE</span><button className="menu-toggle" aria-expanded={menuOpen} aria-controls="navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? 'Close −' : 'Menu +'}</button><nav id="navigation" className={menuOpen ? 'nav open' : 'nav'} aria-label="Main navigation">{[['work','Work'],['about','About'],['experience','Experience'],['skills','Expertise'],['contact','Contact']].map(([id,label]) => <a key={id} href={`#${id}`} onClick={(event) => { setMenuOpen(false); scrollToSection(event, id) }}>{label}<span>↗</span></a>)}</nav></header>
    <main id="main">
      <section className="hero" id="home"><div className="hero-top"><p className="eyebrow"><span className="status-dot"/> ANGELO MIGUEL R. CUA</p><p className="edition">PORTFOLIO / 2026</p></div><div className="hero-layout"><div className="hero-copy"><h1>Data-driven systems.<br/><span>Practical solutions.</span></h1><div className="hero-bottom"><p>Computer Engineering graduate & Data Analyst / Data and Support Engineer.<br/>Combining Power BI insight, system support, software development, and hands-on technical execution.</p><a className="round-link" href="#work" onClick={(event) => scrollToSection(event, 'work')} aria-label="Explore selected work">↓</a></div></div><div className="hero-visual"><div className="visual-label"><span>FORM / FUNCTION</span><span>01—02</span></div><TechnicalArt/><div className="visual-footer"><span>FROM CONCEPT TO REALITY</span><span className="cross">+</span></div></div></div><div className="hero-strip"><span>POWER BI & REPORTING</span><span>+</span><span>IT SUPPORT & NETWORKING</span><span>+</span><span>EMBEDDED SYSTEMS</span></div></section>
      <section id="work" className="section"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2>Ideas made tangible<span>.</span></h2></div><p>Software, hardware, and the systems<br/>that bring them together.</p></div><div className="project-grid">{projects.map((project, index) => <article className={`project project-${project.type}`} key={project.title}><a className="project-image" href={project.url} target="_blank" rel="noreferrer" aria-label={project.linkLabel || `Open ${project.title} CAD model in Onshape (new tab)`}><TechnicalArt type={project.type}/><span className="project-open">↗</span></a><div className="project-meta"><span>{project.category}</span><span>0{index+1}</span></div><a className="project-title" href={project.url} target="_blank" rel="noreferrer"><h3>{project.title}</h3><span>↗</span></a><p>{project.description}</p><div className="project-actions"><a className="project-action" href={project.url} target="_blank" rel="noreferrer">{project.linkLabel || 'View CAD model'}</a>{project.demoUrl && <a className="project-demo-button" href={project.demoUrl} target="_blank" rel="noreferrer">View demo ↗</a>}</div><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></article>)}</div></section>
      <section id="about" className="section about"><p className="eyebrow">02 / THE PERSON BEHIND THE WORK</p><div><h2>Curious by nature.<br/><span>Practical by design.</span></h2><div className="about-copy"><p>I'm Angelo, a Computer Engineering graduate and Data Analyst with hands-on experience in IT support, network infrastructure, data reporting, server installation, and embedded systems. I build and maintain technology that turns operational data and real-world systems into useful, reliable solutions.</p><p>My work spans corporate ICT and security installations, Power BI dashboard development, KPI analysis, full-stack web applications, robotics, and IoT. I combine practical implementation with clear communication, from troubleshooting a workstation to integrating a smart access system for a gym environment.</p></div></div></section>
      <section id="experience" className="section experience"><div><p className="eyebrow">03 / EXPERIENCE & EDUCATION</p><h2>Hands-on.<br/>From the start.</h2></div><div className="career-list">
        <article><p className="career-date">APRIL 2026 — PRESENT</p><h3>Data Analyst & Support Engineer</h3><h4>McAsia Food Trade Corporation</h4><p>Data analysis, reporting, and dashboard development using Power BI; IT support and data management; ICT and security systems installation; and maintenance of network and server infrastructure, including Windows Server, Active Directory, and firewall configuration.</p></article>
        <article><p className="career-date">2019 — PRESENT</p><h3>Freelance Computer Technician & IT Support</h3><h4>Self-employed</h4><p>Hardware diagnostics and repair, operating system and application installation, preventive maintenance, and network troubleshooting for individuals and small businesses.</p></article>
        <article><p className="career-date">2022 — 2026</p><h3>BS in Computer Engineering</h3><h4>STI College Novaliches</h4><p>Previously studied Aeronautical Engineering at FEATI University, 2017 — 2022 (undergraduate).</p></article>
        <article><p className="career-date">NOVEMBER 2025 / RECOGNITION</p><h3>Best in Implementation — Best in Communication</h3><p>ICT-COE Project Symposium and Exhibit.</p></article>
      </div></section>
      <section id="skills" className="section expertise"><div><p className="eyebrow">04 / EXPERTISE</p><h2>A considered<br/>approach.</h2></div><div className="capabilities">{capabilities.map(([number,title,description]) => <div className="capability" key={number}><span>{number}</span><div><h3>{title}</h3><p>{description}</p></div><span className="plus">+</span></div>)}</div></section>
      <section id="contact" className="contact"><p className="eyebrow">05 / WHAT'S NEXT</p><h2>Good ideas deserve<br/><span>great execution.</span></h2><div className="contact-bottom"><p>Let's talk IT infrastructure,<br/>software, and embedded systems.</p><div className="contact-links"><a className="contact-note" href="./Angelo_Miguel_Cua_CV.docx" download>Download my CV</a><a className="contact-note" href="mailto:angelomiguelr.cua@gmail.com">angelomiguelr.cua@gmail.com</a><a className="contact-note" href="https://badjau.github.io/timelight/" target="_blank" rel="noreferrer">Timelight on GitHub Pages</a></div></div><span className="contact-asterisk" aria-hidden="true">✳</span></section>
    </main><footer><a className="brand" href="#home" onClick={(event) => scrollToSection(event, 'home')}>amc<span>✳</span></a><span>© {new Date().getFullYear()} Angelo Miguel R. Cua</span><a href="#home" onClick={(event) => scrollToSection(event, 'home')}>Back to top ↑</a></footer>
  </div>
}
export default App

